//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTripProje2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int ID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Mail { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> Blogid { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
